export const BACKEND="http://localhost:3001"
// export const BACKEND="https://tanet30-back.tp1rc.edu.tw";
export const loginURL="http://localhost:3000/login";
// export const loginURL="https://tanet30.tp1rc.edu.tw/login";
export const FRONTEND="http://localhost:3000"
// export const FRONTEND="https://tanet30.tp1rc.edu.tw";
export const localStateName = "TANET-30";
export const userGroupEnum = ['root', 'foodStaff', 'seminarStaff', 'company', 'user', 'poster', 'cashier'];
export const ticketTypeEnum = ['lunch', 'dinner', 'lunch(vegan)', 'dinner(vegan)'];